// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdfwzsvsaruumshyjsmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkZnd6c3ZzYXJ1dW1zaHlqc21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMzYwNzYsImV4cCI6MjA2MzgxMjA3Nn0.y3xUGKqAo56TR1hwYJzSm1dBTelDULNzrgpfvjaw6F0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);